export { PerformanceMonitor, percentile } from './PerformanceMonitor';
export type { PerformanceReport, PerformanceSnapshot } from './PerformanceMonitor';
export { PerformancePanel } from './PerformancePanel';
export { PerformanceBudgetManager, DEFAULT_BUDGET } from './PerformanceBudget';
export type { PerformanceBudget, RendererStats } from './PerformanceBudget';
export { PerformanceOptimizer } from './PerformanceOptimizer';
export { FrameBudget, FRAME_BUDGET_TABLE } from './FrameBudget';
export type { FrameBudgetSectionId, FrameBudgetSectionDef, FrameBudgetSectionStats } from './FrameBudget';
export { DynamicResolution, DEFAULT_DYNAMIC_RESOLUTION_OPTIONS } from './DynamicResolution';
export type { DynamicResolutionOptions } from './DynamicResolution';
