export { WeaponSystem, Weapon, WeaponType, FireMode, WEAPON_CONFIGS } from './WeaponSystem';
export type { WeaponAction, WeaponActionEvent, WeaponConfig } from './WeaponSystem';
export { WeaponView } from './WeaponView';
export { Raycast, calculateDamage } from './Bullet';
export type { HitInfo, DamageInfo } from './Bullet';
export { MuzzleFlash } from './MuzzleFlash';
export { Projectile } from './Projectile';
export type { ProjectileConfig, ProjectileState } from './Projectile';
export { simulateWeaponRange } from './RangeSimulation';
export type { RangeSample } from './RangeSimulation';
